"""Game

Revision ID: 1348c69cde9b
Revises: 270275f3dce4
Create Date: 2023-11-23 23:18:55.555449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1348c69cde9b'
down_revision: Union[str, None] = '270275f3dce4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('player_1', sa.String(length=36), nullable=True),
    sa.Column('player_2', sa.String(length=36), nullable=True),
    sa.Column('winner', sa.String(length=36), nullable=True),
    sa.Column('status', sa.Enum('STARTING', 'IN_PROGRESS', 'FINISHED', name='gamestatus'), nullable=True),
    sa.Column('board', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['player_1'], ['users.id'], ),
    sa.ForeignKeyConstraint(['player_2'], ['users.id'], ),
    sa.ForeignKeyConstraint(['winner'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_id'), 'game', ['id'], unique=True)
    op.create_table('player_moves',
    sa.Column('player', sa.String(length=36), nullable=True),
    sa.Column('row', sa.Integer(), nullable=True),
    sa.Column('game_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.ForeignKeyConstraint(['player'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_moves_id'), 'player_moves', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player_moves_id'), table_name='player_moves')
    op.drop_table('player_moves')
    op.drop_index(op.f('ix_game_id'), table_name='game')
    op.drop_table('game')
    # ### end Alembic commands ###
